---
- name: create osd bootstrap directory
  file:
    path: /var/lib/ceph/bootstrap-osd
    state: directory

# NOTE (leseb): for version 1.1.0 because https://github.com/ansible/ansible-modules-core/issues/1227
- name: install docker-py
  pip:
    name: docker-py
    version: 1.1.0
